### PR TITLE
Add functionality for Terimnal.app  'new tabs open in current working directory' option

### PR DESCRIPTION
**Pull request by jnmandal**
```update_terminal_cwd ``` is apparently always called on the prompt command but because we redefine it in the bash profile it breaks the osx terminal app's ability to know what the current working directory is. If you simply append this to the end of the new PROMPT_COMMAND definition, it solves this problem.

### CODE REVIEW

**Comment by supertopher** [comment]
I'm a bit confused about what the current problem is given that this work fine for me in terminal as well as for many others... also no other terminal apps use this command, therefore this will break functionality in all other terminal apps (i believe)  if you can show me some screenshots that would be helpful

help me better understand the problem and let's fix it

thanks for the PR =D

oacg251

**Comment by supertopher** [comment]
also this is a setting in terminal.app to open in the same directory

**Comment by jnmandal** [comment]
As I understand it the problem is that terminal.app has a setting called "New tabs open with:" where you can specify a profile (terminal.app profile, not bash) and a working directory. 

screen shot 2015-07-07 at 10 49 58

The feature sadly relies on escape sequences coming from the prompt command. The default prompt command is overwritten with this bash script and thus breaks that feature on terminal.app.

More about why/how here: http://apple.stackexchange.com/questions/49835/how-to-make-mac-terminal-restore-working-directories-when-restarting

I have experienced this issue on both OS X Yosemite and OS X Mavericks. All throughout DBC I never understood why that feature was non-functional on my Mavericks Macbook but I can confirm without a doubt the feature was broken by this prompt command on my OS X Yosemite environment (work computer).

I cannot speak to wether this will break other apps like iTerm though which is a very valid concern.

**Comment by supertopher** [comment]
@jnmandal fixed on master from another PR.  thanks for the help though =D

**Comment by jnmandal** [comment]
Good to hear!

**Pull request closed without merging**
